"""
Django settings for inventoryproject project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', '@ujr-e&a%8m%6!z(+ka16+(sm6cug(h6noe%#p%=6%d2nz5t+#')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

#ALLOWED_HOSTS = ['anujdeshmukh24.pythonanywhere.com']
# Read ALLOWED_HOSTS from environment variable, fallback to default
ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS', 'www.db-solar.co.in,db-solar.co.in,72.60.98.248')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',') if host.strip()]

# Application definition


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}



# Optional: Set token lifetimes
from datetime import timedelta

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
# }


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'dashboard.apps.DashboardConfig',
    'user.apps.UserConfig',
    'customer.apps.CustomerConfig',
    'crispy_forms',
    'firereport.apps.FirereportConfig',
    'widget_tweaks',
    'user.group_filters',
    'active_link',
    'generate_barcodes.apps.GenerateBarcodesConfig',
    'detect_barcodes.apps.DetectBarcodesConfig',
    'product.apps.ProductConfig',
    'inventory.apps.InventoryConfig',
    'transactions.apps.TransactionsConfig',
    'quotation.apps.QuotationConfig',
    'homepage.apps.HomepageConfig',
    'rest_framework',
    'corsheaders',
    'api.apps.ApiConfig',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Temporarily disabled WhiteNoise - using direct file serving via URL patterns instead
    # 'whitenoise.middleware.WhiteNoiseMiddleware',  # Disabled - files served directly via URL patterns
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]


ROOT_URLCONF = 'inventoryproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventoryproject.wsgi.application'


import os
import dj_database_url

DATABASES = {
    'default': dj_database_url.parse(
        os.environ.get('DATABASE_URL'),
        conn_max_age=600
    )
}



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
#TIME_ZONE = 'Asia/kolkata'
USE_I18N = True

USE_L10N = True

USE_TZ = True


CRISPY_TEMPLATE_PACK = 'bootstrap4'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

#STATIC_URL = '/static/'
#STATIC_ROOT = BASE_DIR / 'staticfiles'

#MEDIA_URL = '/media/'
#MEDIA_ROOT = BASE_DIR / 'media'

STATIC_URL = '/static/'

# Directories where Django will collect static files from
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'asert',  # Include asert directory as a static files source
]

# Directory where collectstatic will gather all static files
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration
# WhiteNoise will serve files from STATIC_ROOT (after collectstatic)
# WHITENOISE_USE_FINDERS allows it to also serve from STATICFILES_DIRS
# This is important so files in static/ and asert/ are accessible
WHITENOISE_USE_FINDERS = True  # Enable WhiteNoise to find files in STATICFILES_DIRS (static/ and asert/)
WHITENOISE_AUTOREFRESH = True  # Set to True to auto-refresh when files change (useful for development)
WHITENOISE_ROOT = STATIC_ROOT  # Explicitly set the root directory

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



LOGIN_REDIRECT_URL = 'dashboard-index'
#CUSTOMER_URL = 'customer-index'

LOGIN_URL = 'user-login'

# LOGOUT_REDIRECT_URL = '/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'deshmukh.ssd24@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'pesebzcjfrxnuvsg')
PASSWORD_RESET_TIMEOUT = int(os.environ.get('PASSWORD_RESET_TIMEOUT', '240'))
# SESSION_EXPIRE_AT_BROWSER_CLOSE=False
CORS_ALLOW_ALL_ORIGINS = True



# Session expires after 15 minutes of inactivity
SESSION_COOKIE_AGE = 10 * 60   # 15 minutes (in seconds)

# Expire when browser is closed? (optional)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Reset timer each request (so active users stay logged in)
SESSION_SAVE_EVERY_REQUEST = True

