# Generated by Django 5.2.10 on 2026-05-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_structure_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='estimated_generation',
            field=models.IntegerField(blank=True, help_text='Units/month', null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='panel_count',
            field=models.IntegerField(blank=True, help_text='kW', null=True),
        ),
    ]
