# Generated by Django 5.2.10 on 2026-05-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_survey_building_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='estimated_generation',
            field=models.IntegerField(blank=True, help_text='Units/year', null=True),
        ),
    ]
