# Generated by Django 5.2.10 on 2026-05-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_alter_survey_estimated_generation'),
        ('surveys', '0008_survey_wall_lengths_area_sides'),
    ]

    operations = [
    ]
