# Generated by Django 5.2.10 on 2026-05-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_merge_20260526_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='building_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mtr', max_digits=7, null=True),
        ),
    ]
