# Generated by Django 5.2.10 on 2026-05-05 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0020_quotation_rejection_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_snapshot', models.CharField(blank=True, default='approved', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_approval_records', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='quotation.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
