# Generated by Django 5.2.10 on 2026-05-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0021_quotationapprovalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationapprovalrecord',
            name='hybrid_mode_snapshot',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='quotationapprovalrecord',
            name='payment_mode_snapshot',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='quotationapprovalrecord',
            name='payment_type_snapshot',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='quotationapprovalrecord',
            name='po_date_snapshot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationapprovalrecord',
            name='po_order_no_snapshot',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
