# Generated by Django 5.2.10 on 2026-05-05 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0022_quotationapprovalrecord_payment_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationConversionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_conversion_records', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='conversion_records', to='quotation.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
