# Generated by Django 5.2.10 on 2026-06-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0025_quotation_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationbankdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quotationmaster',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
