# Generated by Django 5.2.10 on 2026-01-31 19:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0096_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('cafa994d-d061-4a7e-ab12-94aa55ea21d2'), primary_key=True, serialize=False),
        ),
    ]
