# Generated by Django 5.2.10 on 2026-02-02 17:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0097_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('c6785bb6-9791-459c-86a7-e152270a7f24'), primary_key=True, serialize=False),
        ),
    ]
