# Generated by Django 5.2.10 on 2026-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0118_customer_mobile_app_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAuthLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('auth_user_id', models.BigIntegerField(db_column='auth_user_id')),
                ('token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'app_auth_links',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_app',
                'managed': False,
            },
        ),
    ]
