# Generated by Django 5.2 — links CRM Revenue to ERP quotation_quotation rows.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
        ('quotation', '0024_alter_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='erp_quotation',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='crm_revenue_rows',
                to='quotation.quotation',
                db_constraint=False,
            ),
        ),
    ]
